markdown: kramdown
permalink: pretty

keep_files:
  [
  "scripts",
  "css",
  "images"
]

title: Freelance-portfolio
email: rendra@rendra.me
description: >- # this means to ignore newlines until "baseurl:"
  This site is freelance-portfolio site based on Travis work on Devtips yuotube channnel.

baseurl: ""

sass:
  sass_dir: _scss
  style: :compressed

exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "scss",
  # "css",
  "validate",
  "misc"
]

