# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rendra P
email: rendra@rendra.me
description: "THINKER // DESIGNER // DREAMER"
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.rendra.me" # the base hostname & protocol for your site
twitter_username: rendrap
github_username: rendrap
# Build settings
#MENU ITEM LIST used in _includes/header.html
menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'A Front-end related blog for everyone.'
  rel-author: 'https://github.com/rendrap'
  rel-publisher: 'http://rendra.me'


#SKILL LIST used in _includes/about.html
skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}

#-------------------------------
# Work Section used in _includes/work.html
projects:
- {name: TYPO International Design Talks, folder: 'proj-1'}
- {name: City-IN website concept, folder: 'proj-2'}
- {name: Crispy Icons, folder: 'proj-3'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4'}
- {name: Fresh It Up, folder: 'proj-5'}
- {name: Timeline Page, folder: 'proj-6'}
- {name: Weather Dashboard, folder: 'proj-7'}
- {name: Stripes & Co, folder: 'proj-8'}

#-------------------------------
# Clients Section used in _includes/client.html
clients:
- {avatar: 'face-aaron.jpg', logo: 'logo1.png', name: 'Scott Summers', title: 'Director of Design, Quebec Int.', quote: '<p><strong>Lorem ipsum dolor sit amet,</strong> consectetur adipisicing elit. Obcaecati quod illo minima eaque modi iusto adipisci libero asperiores reiciendis, dolor delectus quasi quis quia molestiae sunt explicabo facilis commodi nemo recusandae beatae ducimus! Eos, vero!</p> '}
- {avatar: 'face-atariboy.jpg', logo: 'logo2.png', name: 'John Summers', title: 'Director of Design, Quebec Int.', quote: '<p><strong>Lorem ipsum dolor sit amet,</strong> consectetur adipisicing elit. Obcaecati quod illo minima eaque modi iusto adipisci libero asperiores reiciendis, dolor delectus quasi quis quia molestiae sunt explicabo facilis commodi nemo recusandae beatae ducimus! Eos, vero!</p> '}
- {avatar: 'face-jackiesaik.jpg', logo: 'logo3.png', name: 'Rebecca Fall', title: 'Director of Design, Quebec Int.', quote: '<p><strong>Lorem ipsum dolor sit amet,</strong> consectetur adipisicing elit. Obcaecati quod illo minima eaque modi iusto adipisci libero asperiores reiciendis, dolor delectus quasi quis quia molestiae sunt explicabo facilis commodi nemo recusandae beatae ducimus! Eos, vero!</p> '}
- {avatar: 'face-teleject.jpg', logo: 'logo4.png', name: 'Amber ryder', title: 'Director of Design, Quebec Int.', quote: '<p><strong>Lorem ipsum dolor sit amet,</strong> consectetur adipisicing elit. Obcaecati quod illo minima eaque modi iusto adipisci libero asperiores reiciendis, dolor delectus quasi quis quia molestiae sunt explicabo facilis commodi nemo recusandae beatae ducimus! Eos, vero!</p> '}


# Change the site default images and content here!
logo: 'logo.svg'
bg-img: 'nature.jpg'
avatar: 'face.jpg'
blurb: <p><strong>Rendra is passionate web designer & developer.</strong><br>His humble superpower is being able to imagine, create and deliver a web site.</p>






